name: myapp1
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.4
  firebase_auth: ^0.15.4
  firebase_analytics: ^5.0.11
  provider: ^4.0.4
  carousel_slider: ^1.4.1
  carousel_pro: ^1.0.0
  cloud_firestore: ^0.13.4+2
  flutter_staggered_grid_view: ^0.3.0
  flutter_spinkit: "^4.1.2"
  flutter_markdown: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/fblogo.png
     - assets/images/google.png
     - assets/images/logo.png
     - assets/images/logo1.png
     - assets/images/Nfblogo .png
     - assets/images/pt1.png
     - assets/images/pt2.png
     - assets/images/training.png
     - assets/images/twitter.png
     - assets/images/googletrans.png
     - assets/images/1st.jpg
     - assets/images/2nd.jpg
     - assets/images/3rd.jpg
     - assets/images/4th.jpg
     - assets/images/listback.png
     - assets/images/yoga.png
     - assets/images/fitness.jpg
     - assets/images/Yoga.jpg
     - assets/images/diet.jpg
     - assets/images/gym.jpg
     - assets/images/male.png
     - assets/images/female.png
     - assets/images/Yoga_1.png
     - assets/images/types.png
     - assets/images/stress1.jpeg
     - assets/images/stress2.jpg
     - assets/images/digestion.jpeg
     - assets/images/profile_male.png
     - assets/images/profile_female.png
     - assets/images/profile_background.jpg
     - assets/images/gomukhasna.PNG
     - assets/images/shashan.PNG

  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
      - family: galada
        fonts:
          - asset: assets/fonts/galada.ttf

      - family: muli
        fonts:
          - asset: assets/fonts/muli.ttf
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
